services:
  app:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
    networks:
      - default
    depends_on:
      - database
  database:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default
volumes:
  postgres:
    driver: local

networks:
  default:
    driver: bridge